### ISSUE TITLE
Error: Invalid patch string

### ISSUE THREAD

**Issue by zr0n** [clytras/RN061FrescoBuild#1]
When I try to execute the 'yarn fresco-setup' I got the following error:

```
C:\Users\luiz.santos\projetos\zoom\node_modules\diff-match-patch\index.js:2064
      throw new Error('Invalid patch string: ' + text[textPointer]);
      ^
Error: Invalid patch string: @@ -7279,32 +7279,35 @@
    at diff_match_patch.patch_fromText (C:\Users\luiz.santos\projetos\zoom\node_modules\diff-match-patch\index.js:2064:13)
```

**Comment by clytras** [comment]
That's strange because I am working on Windows too.
Maybe your git settings change LF ro CRLF when cloning new repos.

I have created a RN CLI template.

Delete this repo clone and follow the instructions from here https://github.com/clytras/react-native-fresco.

Let me know if it worked for you.

**Comment by zr0n** [comment]
It solved for me. Thank you very much
