### ISSUE TITLE
How to apply custom fresco build to the project?

### ISSUE THREAD

**Issue by JeffGuKang** [clytras/RN061FrescoBuild#3]
Thanks for sharing useful source. 

> 2. Install modules and run fresco-setup script:

>  ```
>  yarn install
>  yarn fresco-setup
> ```

It looks making custom fresco in `<ProjectName>/android/libraries/fresco`.
But there is no description how to apply the custom fresco to my project. 

Could you explain about it?

**Comment by clytras** [comment]
`fresco-setup` does that patching. There is nothing more you have to do in the project to apply fresco and compile it from source.

I suggest you delete this repo and start a new project using a template I've wrote. Check about it here: https://github.com/clytras/react-native-fresco

**Comment by JeffGuKang** [comment]
I applied custom fresco to my in progress project In reference to https://github.com/clytras/react-native-fresco. Thanks.
